# Copyright 2019 Streamsets Inc.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: previewerdeployments.streamsets.com
spec:
  group: streamsets.com
  names:
    kind: PreviewerDeployment
    listKind: PreviewerDeploymentList
    plural: previewerdeployments
    singular: previewerdeployment
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
