# Copyright 2019 Streamsets Inc.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-agent-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.org/ssl-services: streamsets-agent
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "HEAD, OPTIONS, GET, POST, PUT, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-headers: "authorization,content-type,runid,runtype,x-requested-by,x-ss-rest-call"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  tls:
    - secretName: agenttls
  rules:
    - http:
        paths:
          - path: /agent/(.*)
            backend:
              serviceName: streamsets-agent
              servicePort: 31864
          - path: /agent
            backend:
              serviceName: streamsets-agent
              servicePort: 31864
